# Generated by Django 3.2.7 on 2021-12-08 09:46

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_status', models.CharField(choices=[(None, 'Alert Status'), ('At Risk', 'At Risk'), ('On Target', 'On Target')], max_length=100, verbose_name='alert status')),
                ('progress_percentage_quarter', models.FloatField(default=None)),
                ('progress_percentage_school_year', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(choices=[(None, 'Subjects'), ('Araling Panlipunan', 'Araling Panlipunan'), ('English', 'English'), ('ESP', 'ESP'), ('Filipino', 'Filipino'), ('MAPEH', 'MAPEH'), ('Math', 'Math'), ('Science', 'Science'), ('TLE', 'TLE')], max_length=50, verbose_name='subjects')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[(None, 'Choose your gender'), ('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50, verbose_name='gender')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('gradelevel', models.CharField(blank=True, choices=[(None, 'Grade Level'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], max_length=50, verbose_name='grade level')),
                ('section', models.CharField(blank=True, choices=[('Grade 7', (('Aguinaldo', 'Aguinaldo'), ('Jacinto', 'Jacinto'), ('Luna', 'Luna'), ('Mabini', 'Mabini'), ('Rizal', 'Rizal'), ('Silang', 'Silang'))), ('Grade 8', (('Earth', 'Earth'), ('Mercury', 'Mercury'), ('Mars', 'Mars'), ('Jupiter', 'Jupiter'), ('Saturn', 'Saturn'))), ('Grade 9', (('Amethyst', 'Amethyst'), ('Emerald', 'Emerald'), ('Diamond', 'Diamond'), ('Ruby', 'Ruby'), ('Sapphire', 'Sapphire'))), ('Grade 10', (('Curie', 'Curie'), ('Edison', 'Edison'), ('Galileo', 'Galileo'), ('Newton', 'Newton')))], max_length=50, verbose_name='section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='materials/pdf')),
                ('date', models.DateField(default=datetime.date.today)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(None, 'Category'), ('Activity', 'Activity'), ('Quiz', 'Quiz'), ('Exam', 'Exam')], max_length=50, verbose_name='Category')),
                ('url', models.URLField(max_length=500)),
                ('date', models.DateField()),
                ('instruction', models.TextField(max_length=500, verbose_name='Instruction')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[(None, 'Quarters'), ('1st Quarter', '1st Quarter'), ('2nd Quarter', '2nd Quarter'), ('3rd Quarter', '3rd Quarter'), ('4th Quarter', '4th Quarter')], max_length=50, verbose_name='quarters')),
                ('written_work', models.IntegerField(max_length=100)),
                ('performance_task', models.IntegerField(max_length=100)),
                ('grade', models.IntegerField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
