# Generated by Django 3.2.7 on 2021-12-09 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='readingmaterials',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='performance_task',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='written_work',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
