# Generated by Django 3.2.7 on 2021-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[(None, 'Choose your gender'), ('MALE', 'male'), ('FEMALE', 'female')], max_length=50, verbose_name='gender')),
                ('address', models.TextField(max_length=500)),
                ('gradelevel', models.CharField(blank=True, choices=[(None, 'Grade Level'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], max_length=50, verbose_name='grade level')),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
