# Generated by Django 3.2.7 on 2021-12-06 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211206_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='class_subjects',
            new_name='class_subject',
        ),
        migrations.RenameField(
            model_name='classsubjects',
            old_name='user_profile',
            new_name='gradelevel',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='class_subjects',
            new_name='class_subject',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='class_subjects',
            new_name='class_subject',
        ),
        migrations.RenameField(
            model_name='readingmaterials',
            old_name='class_subjects',
            new_name='class_subject',
        ),
        migrations.RemoveField(
            model_name='classsubjects',
            name='user',
        ),
        migrations.AddField(
            model_name='readingmaterials',
            name='instruction',
            field=models.TextField(default=0.00024740227610094015, max_length=500, verbose_name='Instruction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='activity',
            name='instruction',
            field=models.TextField(max_length=500, verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='exams',
            name='instruction',
            field=models.TextField(max_length=500, verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='instruction',
            field=models.TextField(max_length=500, verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='readingmaterials',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
