# Generated by Django 3.2.7 on 2021-12-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211211_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='performance_task',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='quarterly_assessment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='weighted_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='written_work',
            field=models.FloatField(),
        ),
    ]
