# Generated by Django 3.2.7 on 2021-12-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211211_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='gradelevel',
            field=models.TextField(default='', max_length=50, verbose_name='Gradelevel'),
            preserve_default=False,
        ),
    ]
