# Generated by Django 3.2.7 on 2021-12-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_module_gradelevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnalytics',
        ),
    ]
