# Generated by Django 3.2.7 on 2021-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211206_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubjects',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='grade_level',
            field=models.CharField(blank=True, choices=[(None, 'Grade Level'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], max_length=50, verbose_name='Grade Level'),
        ),
    ]
