# Generated by Django 3.2.7 on 2021-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_readingmaterials_prepared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmaterials',
            name='gradelevel',
            field=models.CharField(default='Grade 7', max_length=50, verbose_name='gradelevel'),
            preserve_default=False,
        ),
    ]
