# Generated by Django 3.2.7 on 2021-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='readingmaterials',
            name='date',
            field=models.DateField(),
        ),
    ]
