# Generated by Django 3.2.7 on 2021-12-13 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_readingmaterials_gradelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='file',
            field=models.FileField(default='', upload_to='materials/pdf'),
        ),
    ]
