# Generated by Django 3.2.7 on 2021-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211206_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingmaterials',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='readingmaterials',
            name='url',
        ),
        migrations.AddField(
            model_name='readingmaterials',
            name='file',
            field=models.FileField(default='', upload_to='materials/pdf'),
        ),
    ]
