# Generated by Django 3.2.7 on 2021-12-06 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211207_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterials',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
