# Generated by Django 3.2.7 on 2021-12-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211214_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='total_item',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
