# Generated by Django 3.2.7 on 2021-12-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_module_total_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='total_item',
            field=models.CharField(default=10, max_length=5),
        ),
    ]
