# Generated by Django 3.2.7 on 2021-12-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20211214_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='grade_type',
            field=models.CharField(default='Written Work', max_length=45),
        ),
    ]
