# Generated by Django 3.2.7 on 2021-12-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20211214_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='quarterly_assessmend',
            new_name='quarterly_assessment',
        ),
    ]
