# Generated by Django 3.2.7 on 2021-12-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_quarterly_assessmend_subject_quarterly_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quarter',
            field=models.CharField(default='1st Quarter', max_length=45),
        ),
    ]
