# Generated by Django 3.2.7 on 2021-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_module_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='total_item',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
